---
# Linter rules doc:
# - https://yamllint.readthedocs.io/en/stable/rules.html

extends: default

yaml-files:
  - .ansible-lint

rules:
  braces:
    max-spaces-inside: 1
  comments:
    level: error
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start:
    level: error
  document-end:
    present: false
  empty-lines:
    max: 1
  indentation:
    spaces: 2
  new-lines:
    type: unix
  truthy:
    level: error
    check-keys: false
