---
# This installs Docker and Docker Compose

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: true
  become: true
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: >-
      deb https://download.docker.com/linux/ubuntu
        {{ ansible_distribution_release }} stable
    state: present
  become: true
- name: Install docker-ce and docker-compose
  ansible.builtin.apt:
    # cspell:ignore containerd
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
