---
# Docker Socket Proxy is a security-enhanced proxy for the Docker Socket.

# version: "3.9"

services:
  socketproxy:
    container_name: socketproxy
    # cspell:ignore tecnativa
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    privileged: true
    environment:
      CONTAINERS: 1
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      socket_proxy: ~
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
