---
# Grafana is the open source analytics & monitoring solution for every database.
# - https://grafana.com

# cSpell:enableCompoundWords

# version: "3.9"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.2
    user: $PUID
    volumes:
      - ./containers/grafana/data:/var/lib/grafana
      # yamllint disable-line rule:line-length
      - ./containers/grafana/config/data-sources.yml:/etc/grafana/provisioning/datasources/data-sources.yml:ro
    networks:
      monitoring: ~
    ports:
      - $GRAFANA_HTTP_PORT:3000/tcp
    security_opt:
      - no-new-privileges:true
    depends_on:
      - prometheus
    restart: unless-stopped
