---
# cAdvisor (Container Advisor) provides container users an understanding of the
# resource usage and performance characteristics of their running containers.
# - https://github.com/google/cadvisor

# version: "3.9"

services:
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    privileged: true
    volumes:
      # cspell:ignore rootfs
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      monitoring: ~
    devices:
      # cspell:ignore kmsg
      - /dev/kmsg
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
