---
# cspell:ignore pluggable
# Prometheus exporter for machine metrics, written in Go with pluggable metric
# collectors.

# version: "3.9"

services:
  nodeexporter:
    container_name: nodeexporter
    image: prom/node-exporter:v1.7.0
    command:
      # cspell:ignore rootfs
      - --path.rootfs=/rootfs
    volumes:
      # cspell:ignore rslave
      - /:/rootfs:ro,rslave
    networks:
      monitoring: ~
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
